// Extracts only the game-icons.net icons the game uses and checks that every one exists.
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const collection = JSON.parse(readFileSync(join(root, 'node_modules/@iconify-json/game-icons/icons.json'), 'utf8'))
const all = collection.icons
const W = collection.width || 512, H = collection.height || 512

// 1) Check every `icon` field in the game data
const data = await Promise.all(['skills', 'items', 'actions', 'combat', 'progression'].map(f => import(pathToFileURL(join(root, 'src/game/data', f + '.js')))))
const missing = new Set()
const used = new Set()
const visit = (v, depth = 0) => {
  if (depth > 6 || v == null) return
  if (Array.isArray(v)) return v.forEach(x => visit(x, depth + 1))
  if (typeof v === 'object') {
    for (const [k, x] of Object.entries(v)) {
      if (k === 'icon' && typeof x === 'string') { used.add(x); if (!all[x]) missing.add(x) }
      else visit(x, depth + 1)
    }
  }
}
data.forEach(mod => Object.values(mod).forEach(v => visit(v)))
// plus icons that are generated by functions (tower floors)
const { towerMonster } = data[3]
for (let f = 1; f <= 200; f++) { const ic = towerMonster(f).icon; used.add(ic); if (!all[ic]) missing.add(ic) }

// 2) Names used in components (name="..." or icon: '...') and any loose string that matches
const walk = dir => readdirSync(dir).flatMap(f => { const p = join(dir, f); return statSync(p).isDirectory() ? walk(p) : [p] })
for (const file of walk(join(root, 'src')).filter(f => /\.(vue|js)$/.test(f) && !f.endsWith('icons.json'))) {
  const src = readFileSync(file, 'utf8')
  for (const m of src.matchAll(/['"]([a-z0-9]+(?:-[a-z0-9]+)*)['"]/g)) if (all[m[1]]) used.add(m[1])
  // icon="x", name="x", icon: 'x', toast('x', log('x' (dynamic :icon="..." bindings are skipped)
  for (const m of src.matchAll(/(?:<GameIcon[^>]*?\sname=|(?<![:\w-])icon(?:=|:\s*)|\btoast\(|\blog\()["']([a-z0-9]+(?:-[a-z0-9]+)*)["']/g)) { used.add(m[1]); if (!all[m[1]]) missing.add(m[1] + ` (${file.replace(root, '')})`) }
}

if (missing.size) {
  console.error('Unknown icons:', [...missing].join(', '))
  process.exit(1)
}
const out = {}
for (const n of [...used].sort()) if (all[n]) out[n] = [all[n].body, all[n].width || W, all[n].height || H]
writeFileSync(join(root, 'src/game/icons.json'), JSON.stringify(out))
console.log(`${Object.keys(out).length} icons written to src/game/icons.json`)
